env:
  global:
  - CIBW_BUILD="cp36-* cp37-* cp38-*"
  - CIBW_BEFORE_BUILD_LINUX="apt update && apt install -y libtiff5-dev libhdf5-dev"
  - CIBW_ARCHS="auto64"
  - CIBW_MANYLINUX_X86_64_IMAGE="manylinux_2_24"
  - TWINE_USERNAME=__token__
matrix:
  include:
  - language: python
    os: linux
    sudo: required
    python: '3.7'
    services:
    - docker
install:
- python3 -m pip install cibuildwheel==1.10.0
script:
- python3 -m cibuildwheel --output-dir wheelhouse
after_success:
- python3 -m pip install twine
- python3 -m twine upload --repository testpypi wheelhouse/*.whl
